@host = http://localhost:3000
@userId = 64f60f5e8d6f70be8d752b65

### Create user
POST {{host}}/users/register
Content-Type: application/json

{
  "name": "Nikita",
  "email": "nikita@example.com",
  "password": "qwerty12",
  "userType": "pro"
}

### Upload user avatar
POST {{host}}/users/{{userId}}/avatar
Content-Type: multipart/form-data; boundary=----SixCitiesBoundary

------SixCitiesBoundary
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/jpeg

< ./markup/img/avatar-max.jpg
------SixCitiesBoundary--
