export enum Component {
  Application = 'Application',
  Config = 'Config',
  Logger = 'Logger',
  DatabaseClient = 'DatabaseClient',
  ExceptionFilter = 'ExceptionFilter',
  UserController = 'UserController',
  OfferController = 'OfferController',
  FavoriteController = 'FavoriteController',
  UserModel = 'UserModel',
  OfferModel = 'OfferModel',
  CommentModel = 'CommentModel',
  FavoriteModel = 'FavoriteModel',
  UserService = 'UserService',
  OfferService = 'OfferService',
  CommentService = 'CommentService',
  FavoriteService = 'FavoriteService',
}
